CREATE TABLE [dbo].[Books] (
    [Id]        UNIQUEIDENTIFIER NOT NULL,
    [Publisher] NVARCHAR (MAX)   NOT NULL,
    [ISBN]      NVARCHAR (MAX)   NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

