CREATE TABLE [dbo].[OrderLines] (
    [Id]        UNIQUEIDENTIFIER NOT NULL,
    [UnitPrice] DECIMAL (10, 2)  NOT NULL,
    [Amount]    INT              NOT NULL,
    [Discount]  DECIMAL (10, 2)  NOT NULL,
    [OrderId]   UNIQUEIDENTIFIER NOT NULL,
    [ProductId] UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

